spring:
  profiles: default
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/turtle?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: mysql
    password: mysql
    initialSize: 10
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    testWhileIdle: true
    validationQuery: select 'x'
  http:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  velocity:
    charset: UTF-8
    properties.input.encoding: UTF-8
    properties.output.encoding: UTF-8 
    resourceLoaderPath: classpath:templates/
    suffix: .vm
  jmx.default-domain: rest.turtlebone
  dubbo:
    server: true
    application.id: tb-rest
    application.name: tb-rest
    registry.address: zookeeper://127.0.0.1:2181
    protocol.name: dubbo
    protocol.port: 20882
    scan: com.turtlebone.rest
server:
  port: 8086
  contextPath: /
mybatis:
  mapperLocations: classpath:mapper/*.xml
redis.expireTime: 60
constants:
  excludeRegex: query
---
spring:
  profiles: prod
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://turtlebone.top:3306/turtle?allowMultiQueries=true
    username: mysql
    password: mysql
    initialSize: 10
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    testWhileIdle: true
    validationQuery: select 'x'
  http:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  velocity:
    charset: UTF-8
    properties.input.encoding: UTF-8
    properties.output.encoding: UTF-8 
    resourceLoaderPath: classpath:templates/
    suffix: .vm
  jmx.default-domain: rest.turtlebone
  dubbo:
    server: true
    application.id: tb-rest
    application.name: tb-rest
    registry.address: zookeeper://127.0.0.1:2181
    protocol.name: dubbo
    protocol.port: 20882
    scan: com.turtlebone.rest
server:
  port: 8086
  contextPath: /
mybatis:
  mapperLocations: classpath:mapper/*.xml
redis.expireTime: 3600
constants:
  excludeRegex: query